services:
  php:
    build:
      context: .
      dockerfile: ./docker/staging/Dockerfile
      args:
        UID: 1000
        GID: 1000
    container_name: intconnect-php-staging
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./src/.env.staging
    environment:
      TZ: Europe/Bucharest
    working_dir: /var/www
    volumes:
      - './src:/var/www'
      - /var/www/vendor
      - /var/www/public/build
    networks:
      - intconnect-staging

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: intconnect-nginx-staging
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - '8080:80'
    environment:
      FPM_HOST: "php:9000"
      TZ: Europe/Bucharest
    volumes:
      - './src:/var/www'
    networks:
      - intconnect-staging

  node:
    image: node:20
    container_name: intconnect-node-staging
    working_dir: /var/www
    volumes:
      - './src:/var/www'
    tty: true
    networks:
      - intconnect-staging

  database:
    image: mariadb:11.0
    container_name: intconnect-database-staging
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 1m
    ports:
      - "3306:3306"
    hostname: database
    volumes:
      - "database-staging:/var/lib/mysql"
    stop_signal: SIGINT
    env_file:
      - ./src/.env.staging
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-intconnect}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE}
      TZ: Europe/Bucharest
    networks:
      - intconnect-staging

networks:
  intconnect-staging:

volumes:
  database-staging:
