# docker-compose.staging.yml
version: '3.8'

services:
  php:
    build:
      context: . # Build context is the project root
      dockerfile: ./docker/Dockerfile.prod
    image: ghcr.io/${GITHUB_USERNAME}/intconnect-stg:latest # Use the pre-built image from the CI/CD pipeline
    container_name: intconnect-stg-php
    restart: unless-stopped
    env_file:
      - ./src/.env.staging # Load environment variables from the .env.staging file
    volumes:
      - ./src/storage:/var/www/storage # Persistent storage for logs, sessions, etc.
    networks:
      - intconnect-stg
    depends_on:
      database:
        condition: service_healthy

  nginx:
    build:
      context: ./docker
      dockerfile: Dockerfile.nginx
    container_name: intconnect-stg-nginx
    restart: unless-stopped
    ports:
      - "8080:80" # Expose staging on port 8080
    networks:
      - intconnect-stg
    depends_on:
      - php

  database:
    image: mariadb:11.0
    container_name: intconnect-stg-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 1m
    env_file:
      - ./src/.env.staging # Load database credentials from the .env.staging file
    volumes:
      - stg-database:/var/lib/mysql
    networks:
      - intconnect-stg

networks:
  intconnect-stg:
    name: intconnect-stg-net

volumes:
  stg-database:
    name: intconnect-stg-db-data
