name: Manage Staging Environment

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Start or stop staging environment'
        required: true
        type: choice
        options:
          - start
          - stop

jobs:
  manage-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        env:
          HCLOUD_TOKEN: ${{ secrets.HETZNER_TOKEN }}
        run: terraform -chdir=terraform init -input=false

      - name: Get Server IP
        id: tf_output
        env:
          HCLOUD_TOKEN: ${{ secrets.HETZNER_TOKEN }}
        run: |
          ip=$(terraform -chdir=terraform output -raw server_ip)
          echo "SERVER_IP=$ip" >> $GITHUB_ENV

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Start/Stop Staging
        run: |
          PROJECT_PATH="/home/ubuntu/intconnect"

          if [ "${{ github.event.inputs.action }}" == "start" ]; then
            echo "Starting staging..."
            ssh -o StrictHostKeyChecking=no ubuntu@${{ env.SERVER_IP }} \
              "sudo docker compose -f ${PROJECT_PATH}/docker-compose.staging.yml up -d"
            echo "Staging started."

          else
            echo "Stopping staging..."
            ssh -o StrictHostKeyChecking=no ubuntu@${{ env.SERVER_IP }} \
              "sudo docker compose -f ${PROJECT_PATH}/docker-compose.staging.yml down"
            echo "Staging stopped."
          fi
